services:
  ai_developer_ts:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        CONTAINER_USER: vscode
        CONTAINER_WORKDIR: /workspace
    network_mode: "host"
    volumes:
      - ..:/workspace
    env_file:
      - ../.env
    command: >
      /bin/sh -c '
      sudo service docker start &&
      /bin/bash
      '
    tty: true
    stdin_open: true
    privileged: true
